---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3091105299-VoLocpctkZpxoC3Jz91Xg2etZ1WXM6SOf3sjPDC
:access_token_secret: FApIGAbQ6SVU9RDAzN1wlUzlgiaie7uBfNMBOInIthhNj
